In [1]:
import numpy as np

In [2]:
list_1 = [1,2,3,4,5]
np.array(list_1)

array([1, 2, 3, 4, 5])

### arange, ones, zeros

In [3]:
np.arange(0,20,5)

array([ 0,  5, 10, 15])

In [4]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [6]:
np.ones((5,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

### Linspace

In [7]:
np.linspace(0,2,10)

array([0.        , 0.22222222, 0.44444444, 0.66666667, 0.88888889,
       1.11111111, 1.33333333, 1.55555556, 1.77777778, 2.        ])

### Creating Identity Matrix

In [9]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

### rand, randn and randint

In [11]:
np.random.rand(3,2)  # Uniform Distribution

array([[0.73888953, 0.07237185],
       [0.45577471, 0.97583478],
       [0.01330396, 0.99350225]])

In [13]:
np.random.randn(2,2) # Standard  normal Distribution

array([[ 0.01760434,  0.75575113],
       [ 0.53338819, -0.12759022]])

In [14]:
np.random.randint(1,10,5)

array([2, 3, 9, 7, 6])

### Reshape

In [17]:
array_1 = np.arange(16)
array_1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [20]:
array_1.reshape(4,4) # Number of elements should match

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

### min, max, argmin, argmax

In [27]:
array_2 = np.random.randint(0,20,10)
array_2

array([ 2,  9, 18,  7, 11, 13, 18, 15,  7,  1])

In [34]:
np.sort(array_2)

array([ 1,  2,  7,  7,  9, 11, 13, 15, 18, 18])

In [35]:
array_2.min()

1

In [36]:
array_2.max()

18

In [37]:
array_2.argmin() # Gives the index

0

In [38]:
array_2.argmax()

8

In [39]:
array_2.shape

(10,)

### Slice 

In [40]:
array_1 = np.arange(0,21)
array_1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20])

In [41]:
array_1[0:5] 

array([0, 1, 2, 3, 4])

In [42]:
array_1[0:5] = 100
array_1

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20])

### copy

In [47]:
array_2 = np.arange(0,11)
array_2

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [48]:
array_3 = array_2[0:3]
array_3

array([0, 1, 2])

In [49]:
array_3 [:] = 100
array_3

array([100, 100, 100])

In [52]:
array_2

array([100, 100, 100,   3,   4,   5,   6,   7,   8,   9,  10])

In [53]:
# Use copy to preserve the value of original array

In [54]:
array_2 = np.arange(0,11)
array_3 = array_2.copy()

In [58]:
array_3[:] = 100
print(array_2)
print('\n')
print(array_3)

[ 0  1  2  3  4  5  6  7  8  9 10]


[100 100 100 100 100 100 100 100 100 100 100]


### 2D Array Slicing

In [60]:
array_2d = np.array([[1,2,3],[4,5,6],[7,8,9]])
array_2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [61]:
array_2d[0,1] # Single Bracket Notation

2

In [62]:
array_2d[0][1] # Double Bracket Notation

2

### Operations on Array

In [67]:
array = np.arange(0,5)
array

array([0, 1, 2, 3, 4])

In [68]:
array -2

array([-2, -1,  0,  1,  2])

In [71]:
array = array * array
array

array([ 0,  1,  4,  9, 16])

In [72]:
np.sqrt(array)

array([0., 1., 2., 3., 4.])